Checkpoint1
CustadialShip/phoneshop pull request #1
Opened 2021-11-18 14:19 UTC by CustadialShip

2021-11-19 12:59 UTC, devjohnsmith1 requested changes

2021-11-19 12:59 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/ColorRowMapper.java
> +        color.setId(resultSet.getLong("id"));
Вынеси строковые значения в переменные

2021-11-19 12:59 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        };
Вынеси в отдельный private метод вроде getPhoneFieldsObject

2021-11-19 12:59 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        jdbcTemplate.update("insert into phones values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", phoneFields);
строки -> константы

2021-11-19 12:59 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +            jdbcTemplate.update("insert into phone2color values (?, ?)", new Object[]{lastIndex, color.getId()});
Посмотри, как обновить не с помощью цикла, а jdbcTemplate.batchUpdate

2021-11-19 12:59 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/PhoneRowMapper.java
> +        phone.setDescription(resultSet.getString("description"));
вынеси в отдельный метод

2021-11-19 12:59 UTC, devjohnsmith1 commented on core/src/main/test/java/com/es/core/model/phone/JdbcPhoneDaoTest.java
> +}
слово test не нужно + поменяй названия тестовых методов на конкретные - "should....when....method"

2021-11-22 09:18 UTC, CustadialShip commented on core/src/main/java/com/es/core/model/phone/PhoneRowMapper.java
> +        phone.setDescription(resultSet.getString("description"));
Мне кажется это лишним, так как функционал метода mapRow заключается только в этих строчках

2021-11-22 13:11 UTC, merged

2021-11-22 13:20 UTC, devjohnsmith1 requested changes

2021-11-22 13:20 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +            Optional<Color> color = jdbcTemplate.query(SELECT_FROM_COLORS_WHERE_ID,
Избегай обращений к базе данных в цикле, используй оператор IN в запросе (подгружай сразу все значения)

2021-11-22 13:20 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/Color.java
> +    public boolean equals(Object o) {
Используй java.util.Objects.equals в реализации этого метода (почитай подробнее)

2021-11-22 13:20 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/Color.java
> +    }
Используй java.util.Objects.hash. Не стоит использовать magic numbers в методах.

2021-11-22 13:20 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/Phone.java
> +
Здесь отступ не нужен

2021-11-22 13:20 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/Phone.java
> +        if (model != null ? !model.equals(phone.model) : phone.model != null) return false;
Очень громоздкий equals. Используй в реализации Objects.equals

2021-11-22 13:20 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/Phone.java
> +        result = 31 * result + (brand != null ? brand.hashCode() : 0);
Громоздкий hashcode + magic numbers -> Objects.equals

2021-11-22 13:20 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/Phone.java
> +                ", displayResolution='" + displayResolution + '\'' +
Очень много конкатенаций строк, посмотри, как делать это лучше - StringJoiner, например