Checkpoint #2
CustadialShip/phoneshop pull request #4
Opened 2021-11-25 23:18 UTC by CustadialShip

2021-11-26 06:01 UTC, devjohnsmith1 requested changes

2021-11-26 06:01 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/cart/HttpSessionCartService.java
> +            throw new CartItemNotFindException("CartItem is not found");
Выноси строчки в константы. Константы в самом классе эксепшна можешь хранить

2021-11-26 06:01 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/color/Color.java
>          return result;
Не пиши захардкоженный hashCode, используй Objects.hash

2021-11-26 06:01 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +    public static final String SELECT_FROM_PHONES_OFFSET = "select * from phones inner join stocks on phones.id = stocks.phoneId where stock - reserved > 0 offset ";
Упомяни в самом названии запроса, что он достаёт те телефоны, основываясь на stock

2021-11-26 06:01 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +            throw new PhoneNotFindException("The phone(" + key + " is not found");
Message сохраняй в константы (в классе эксепшна), а здесь уже можешь формировать финальное сообщение

2021-11-26 06:01 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        List<Phone> phoneList = jdbcTemplate.query(SELECT_FROM_PHONES_OFFSET + offset + LIMIT + limit, new PhoneRowMapper());
Избегай конкатенации строк. Посмотри, как передать параметры в query

2021-11-26 06:01 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        return stringBuilder.append(SELECT_FROM_PHONES_INNER_JOIN_STOCKS_ON_PHONES_ID_STOCKS_PHONE_ID_WHERE_STOCK_RESERVED_0_AND_DISPLAY_SIZE_INCHES_0_AND_PRICE_0_AND_LOWER_MODEL_LIKE)
Переменная очень длинная. Не стоит описывать всё, что прописано в query, назови функционально - что делает этот select

2021-11-26 06:01 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +    private String sqlCreator(int offset, int limit, SortField sortField, SortOrder sortOrder, String searchText) {
Укажи в названии метода, какую конкретную конкретную query он возвращает

2021-11-26 06:01 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/Stock.java
> +        Stock stock1 = (Stock) o;
Почему stock1? Не стоит нумеровать переменные

2021-11-26 06:01 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/Stock.java
> +    }
Избегай конкатенации строк

2021-11-26 06:01 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/service/PaginationServiceImpl.java
> +    public static final int NUMBER_OF_PAGINATION_BUTTON = 5;
Можно в описании переменной указать, что это DEFAULT VALUE

2021-11-26 06:01 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/service/PaginationServiceImpl.java
> +        }
Потенциальный IndexOutOfBoundsException. Перепиши на более безопасный цикл

2021-11-26 06:01 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/service/PaginationServiceImpl.java
> +        return (pageNumber - 1) * PHONES_PER_PAGE;
Добавь проверку pageNumber - он может оказаться отрицательным

2021-11-26 06:01 UTC, devjohnsmith1 commented on core/src/main/test/java/com/es/core/model/phone/JdbcPhoneDaoTest.java
> +import static org.junit.Assert.*;
Лишние импорты - вряд ли тебе нужны все классы

2021-11-26 06:01 UTC, devjohnsmith1 commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
> +    private CartService cartService;
отделяй визуально константы от других филдов

2021-11-26 06:01 UTC, devjohnsmith1 commented on web/src/main/java/com/es/phoneshop/web/controller/pages/dto/CartAddForm.java
> +    private Integer quantity;
отделяй отступами поля с аннотациями - легче читать

2021-11-26 09:34 UTC, CustadialShip commented on core/src/main/java/com/es/core/service/PaginationServiceImpl.java
> +        }
Тут вроде не может быть IndexOutOfBoundsException, так как используется add

2021-11-28 06:43 UTC, devjohnsmith1 requested changes

2021-11-28 06:43 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/model/phone/Phone.java
> +        return Objects.equals(brand, phone.brand) && Objects.equals(model, phone.model);
Objects.equals(brand, phone.brand) && Objects.equals(model, phone.model) эквивалентно всем 3-м строчкам. В двух ифах выше нет смысла

2021-11-28 06:43 UTC, devjohnsmith1 commented on core/src/main/java/com/es/core/service/PaginationServiceImpl.java
> +        }
Перепиши генерацию последовательности с помощью IntStream

2021-11-29 13:37 UTC, devjohnsmith1 approved these changes

2021-11-30 10:26 UTC, merged